apiVersion: v1
kind: ReplicationController
metadata:
  name: cbs
spec:
  replicas: 3
  selector: 
    app: cbs
  template:
    metadata:
      name: cbs
      labels:
        app: cbs
    spec:
      containers:
      - name: cbs
        image: lokeshm89/cbs
        ports:
        - containerPort:  8080
